BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TRANSACCIONES';
  EXECUTE IMMEDIATE 'DROP TABLE PASOS_PEAJES_PENDIENTES';
  EXECUTE IMMEDIATE 'DROP TABLE PEAJES';
  EXECUTE IMMEDIATE 'DROP TABLE MEMBRESIAS_CLIENTE';
  EXECUTE IMMEDIATE 'DROP TABLE TIPOS_MEMBRESIA';
  EXECUTE IMMEDIATE 'DROP TABLE VEHICULOS_TAG';
  EXECUTE IMMEDIATE 'DROP TABLE CLIENTES';
  EXECUTE IMMEDIATE 'DROP TYPE TYP_NOTIFICACION_PAYLOAD';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/