--==============================================================================
-- 1. TABLAS PRINCIPALES
--==============================================================================
CREATE TABLE CLIENTES (
ID_CLIENTE NUMBER(10) NOT NULL PRIMARY KEY,
NOMBRE_CLIENTE VARCHAR2(150) NOT NULL,
SALDO_ACTUAL NUMBER(12, 2) DEFAULT 0 NOT NULL
);

CREATE TABLE VEHICULOS_TAG (
ID_TAG VARCHAR2(20) NOT NULL PRIMARY KEY,
ID_CLIENTE NUMBER(10) NOT NULL REFERENCES CLIENTES(ID_CLIENTE),
PLACA_VEHICULO VARCHAR2(10) NOT NULL,
ESTADO VARCHAR2(10) DEFAULT 'ACTIVO' NOT NULL -- ACTIVO, ROBADO, INACTIVO 
);

CREATE TABLE TIPOS_MEMBRESIA (
ID_MEMBRESIA NUMBER(3) NOT NULL PRIMARY KEY,
NOMBRE_MEMBRESIA VARCHAR2(100) NOT NULL,
APLICA_COMISION CHAR(1) DEFAULT 'S' NOT NULL -- 'S' o 'N'
);

CREATE TABLE MEMBRESIAS_CLIENTE (
ID_MEMBRESIA_CLIENTE NUMBER(12) NOT NULL PRIMARY KEY,
ID_CLIENTE NUMBER(10) NOT NULL REFERENCES CLIENTES(ID_CLIENTE),
ID_MEMBRESIA NUMBER(3) NOT NULL REFERENCES TIPOS_MEMBRESIA(ID_MEMBRESIA),
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE -- NULL = indefinidamente activa
);

CREATE TABLE PEAJES (
ID_PEAJE NUMBER(5) NOT NULL PRIMARY KEY,
NOMBRE_PEAJE VARCHAR2(100),
EXENTO_COMISION CHAR(1) DEFAULT 'N' NOT NULL -- 'S' o 'N'
);

CREATE TABLE PASOS_PEAJES_PENDIENTES (
ID_PASO NUMBER(20) NOT NULL PRIMARY KEY,
ID_TAG VARCHAR2(20) NOT NULL,
ID_PEAJE NUMBER(5) NOT NULL,
FECHA_HORA_PASO DATE NOT NULL,
VALOR_PEAJE NUMBER(10, 2) NOT NULL,
ESTADO VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL, -- PENDIENTE, PROCESANDO, ERROR, OK
MENSAJE_ERROR VARCHAR2(500),
ID_LOTE_PROCESO VARCHAR2(50)
);

CREATE TABLE TRANSACCIONES (
ID_TRANSACCION NUMBER(20) NOT NULL PRIMARY KEY,
ID_PASO NUMBER(20) NOT NULL,
ID_CLIENTE NUMBER(10) NOT NULL,
FECHA_PROCESO DATE DEFAULT SYSDATE,
VALOR_BASE NUMBER(10, 2) NOT NULL,
VALOR_DESCUENTO NUMBER(10, 2) DEFAULT 0,
VALOR_COMISION NUMBER(10, 2) DEFAULT 0,
VALOR_TOTAL_COBRADO NUMBER(12, 2) NOT NULL,
SALDO_ANTERIOR NUMBER(12, 2),
SALDO_FINAL NUMBER(12, 2),
ESTADO_TRANSACCION VARCHAR2(25) NOT NULL,
DESCRIPCION VARCHAR2(255)
);