CREATE OR REPLACE TYPE TYP_NOTIFICACION_PAYLOAD AS OBJECT (
ID_CLIENTE NUMBER(10),
ID_PASO NUMBER(20),
TIPO_NOTIFICACION VARCHAR2(30), -- 'PROCESADO_OK', 'ERROR_SALDO', 'ERROR_TAG'
FECHA_EVENTO DATE,
MENSAJE VARCHAR2(500),
DATOS_ADICIONALES VARCHAR2(1000)
);
/