BEGIN
DBMS_AQADM.CREATE_QUEUE_TABLE(queue_table => 'QT_NOTIFICACIONES',
queue_payload_type => 'TYP_NOTIFICACION_PAYLOAD');
DBMS_AQADM.CREATE_QUEUE(queue_name => 'Q_NOTIFICACIONES', queue_table =>
'QT_NOTIFICACIONES');
DBMS_AQADM.START_QUEUE(queue_name => 'Q_NOTIFICACIONES');
END;
/