CREATE OR REPLACE PACKAGE PKG_PROCESOS_FLYPASS AS
    BATCH_SIZE CONSTANT PLS_INTEGER := 500;
    
    PROCEDURE PROCESAR_PASOS_PEAJES(p_max_registros IN PLS_INTEGER DEFAULT 10000);
    
END PKG_PROCESOS_FLYPASS;
/