CREATE OR REPLACE PACKAGE PKG_NOTIFICACIONES_CONSUMER AS
    -- Procedimiento para procesar mensajes de la cola
    PROCEDURE PROCESAR_MENSAJES_ENCOLADOS(p_limit IN PLS_INTEGER DEFAULT 100);
END PKG_NOTIFICACIONES_CONSUMER;
/