-- Índices para optimizar las consultas más frecuentes
CREATE INDEX IDX_PASOS_PENDIENTES_ESTADO ON PASOS_PEAJES_PENDIENTES(ESTADO, ID_LOTE_PROCESO);
CREATE INDEX IDX_PASOS_TAG ON PASOS_PEAJES_PENDIENTES(ID_TAG);
CREATE INDEX IDX_PASOS_PEAJE ON PASOS_PEAJES_PENDIENTES(ID_PEAJE);
CREATE INDEX IDX_VEHICULOS_TAG_ESTADO ON VEHICULOS_TAG(ESTADO);
CREATE INDEX IDX_MEMBRESIAS_CLIENTE_ACTIVAS ON MEMBRESIAS_CLIENTE(ID_CLIENTE, ID_MEMBRESIA, FECHA_INICIO, FECHA_FIN);
CREATE INDEX IDX_TRANSACCIONES_CLIENTE ON TRANSACCIONES(ID_CLIENTE);
CREATE INDEX IDX_TRANSACCIONES_PASO ON TRANSACCIONES(ID_PASO);